# Generated by Django 4.0.6 on 2022-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfees',
            name='class_name',
            field=models.CharField(choices=[('Creche', 'Creche'), ('PreKg', 'PreKg'), ('Kindergarten', 'Kindergarten'), ('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5')], max_length=30),
        ),
    ]
