# Generated by Django 4.0.6 on 2022-07-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_classfees_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='subclass_name',
            new_name='subclass',
        ),
    ]
