# Generated by Django 4.0.6 on 2022-07-15 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_user_pending_photo_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/users/'),
        ),
        migrations.AlterField(
            model_name='pendingphoto',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
