# Generated by Django 4.0.6 on 2022-07-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_class_name_classfees_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'staff'), ('student', 'student')], default='student', max_length=10),
        ),
    ]
