# Generated by Django 4.0.6 on 2022-07-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_delete_blog_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingphoto',
            name='photo',
            field=models.ImageField(upload_to='uploads/users/'),
        ),
    ]
