# Generated by Django 4.0.6 on 2022-07-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_pendingphoto_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='_class',
        ),
        migrations.AddField(
            model_name='class',
            name='class_name',
            field=models.CharField(choices=[('creche', 'Creche'), ('prekg', 'PreKindergarten'), ('kg', 'Kindergarten'), ('nur1', 'Nursery 1'), ('nur2', 'Nursery 2'), ('g1', 'Grade 1'), ('g2', 'Grade 2'), ('g3', 'Grade 3'), ('g4', 'Grade 4'), ('g5', 'Grade 5')], default=('prekg', 'PreKindergarten'), max_length=30),
        ),
        migrations.AddField(
            model_name='class',
            name='new_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='return_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
