# Generated by Django 4.0.4 on 2022-07-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_test_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
