# Generated by Django 4.0.6 on 2022-07-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_class_options_remove_class__class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(choices=[('creche', 'Creche'), ('prekg', 'PreKindergarten'), ('kg', 'Kindergarten'), ('nur1', 'Nursery 1'), ('nur2', 'Nursery 2'), ('g1', 'Grade 1'), ('g2', 'Grade 2'), ('g3', 'Grade 3'), ('g4', 'Grade 4'), ('g5', 'Grade 5')], max_length=30),
        ),
        migrations.AlterField(
            model_name='class',
            name='new_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='return_fee',
            field=models.IntegerField(),
        ),
    ]
