# Generated by Django 4.0.4 on 2022-07-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(),
        ),
    ]
