# Generated by Django 4.0.6 on 2022-07-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_class_class_name_alter_class_new_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(choices=[('cleaner', 'Cleaner'), ('teacher', 'Teacher'), ('newheadteacher', 'Head Teacher'), ('norole', 'No Role'), ('security', 'Security')], max_length=20),
        ),
    ]
