# Generated by Django 4.0.6 on 2022-07-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_staff_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(choices=[('cleaner', 'Cleaner'), ('teacher', 'Teacher'), ('headteacher', 'Head Teacher'), ('norole', 'No Role'), ('security', 'Security')], max_length=20),
        ),
    ]
