# Generated by Django 4.0.4 on 2022-07-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='option_id',
            field=models.IntegerField(default=1),
        ),
    ]
