# Generated by Django 4.0.6 on 2022-07-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='new_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='return_fee',
            field=models.IntegerField(default=0),
        ),
    ]
