# Generated by Django 4.0.6 on 2022-08-06 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_option_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.TimeField(default=datetime.time(0, 10)),
        ),
    ]
