# Generated by Django 4.0.6 on 2022-07-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_class_new_fee_alter_class_return_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='currrent_class',
            new_name='current_class',
        ),
    ]
