# Generated by Django 4.0.6 on 2022-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingphoto',
            name='photo',
            field=models.ImageField(upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='users/default.png', null=True, upload_to='users/'),
        ),
    ]
