# Generated by Django 4.0.6 on 2022-08-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_alter_pendingphoto_photo_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
