# Generated by Django 4.0.6 on 2022-08-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_remove_question_test_remove_test_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='/users/default.png', null=True, upload_to='uploads/users/'),
        ),
    ]
