# Generated by Django 4.0.6 on 2022-08-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_alter_pendingphoto_photo_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='uploads/users/default.png', null=True, upload_to='uploads/users/'),
        ),
    ]
