# Generated by Django 4.0.6 on 2022-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/blogs/')),
                ('date', models.DateField()),
            ],
        ),
    ]
