# Generated by Django 4.0.6 on 2022-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0003_rename_contactlist_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='random',
            name='photo',
            field=models.ImageField(upload_to='random/'),
        ),
    ]
