# Generated by Django 4.0.6 on 2022-07-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0005_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
