# Generated by Django 4.0.6 on 2022-07-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_page', '0006_alter_message_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='time',
        ),
    ]
